spring:
  application:
    name: up42-features-challenge
  profiles:
    active: development
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
      show-sql: true
  liquibase:
    change-log: classpath:/liquibase/master.yaml
    enabled: true

logging:
  level:
    com.up42.features: debug

---
spring:
  profiles: development
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost/application-db?user=postgres&password=password

---
spring:
  profiles: prod
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}?user=postgres&password=${DATABASE_PASSWORD}

logging:
  level:
    com.up42.features: info